name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "npm"
      - name: Check for vulnerabilities with Snyk
        run: npx --yes snyk test

  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      DYNAMO_DB_PORT: 8000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "npm"
      - name: Docker compose
        run: |
          docker compose up --wait
      - name: Install, lint and test
        run: |
          npm ci --ignore-scripts
          npm run lint
          npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .
