name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "npm"
      - name: Lint
        run: |
          npm ci --ignore-scripts
          npm run lint

  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      DYNAMO_DB_PORT: 8000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "npm"
      - name: Docker compose
        run: |
          docker compose up --wait
      - name: Test and audit
        run: |
          npm ci --ignore-scripts
          npm audit
          npm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .
